### ISSUE TITLE
7/7 Completing Minecraft Initialization

### ISSUE THREAD

**Issue by keremlov** [Unhook/Celestial-Journey#40]
7/7 Completing Minecraft Initialization
The game stuck here and won't open. I don't know what to do.

**Comment by ariosos** [comment]
The first time I installed it, it crashed for me, then started up again normally. I've noticed this happening on some modpacks (at least once before) - I think it's the case of a mod wanting a config option that hasn't been updated in the correct order, but corrects itself on reloading.

Also, make sure you have 4 gigs of ram. (That's why my allocated RAM is set to by default - I think if the bar is yellow or red, you don't have enough. Might need 2 gigs)

**Comment by keremlov** [comment]
I'm sorry but it has been 9 days and your solution is " try opening it again"?? Ofcourse I have tried re-opening it. I give mc 6 GBs of ram..

**Comment by keremlov** [comment]
I have tried talking to the pack developer but he disappeared... Can't see em online on discord. No one really helps me on discord or here so if they don't want us to play, sure..

**Comment by Unhook** [comment]
Provide the log.

**Comment by keremlov** [comment]
[latest.log](https://github.com/Unhook/Celestial-Journey/files/4807838/latest.log)
